version: '2'
services:
  hackazon-www:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - hackazon-db

  hackazon-db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=hackazon
      - MYSQL_DATABASE=hackazon
      - MYSQL_USER=hackazon
      - MYSQL_PASSWORD=hackazon
    restart: always
    volumes:
      - ./db_init/hackazon/:/docker-entrypoint-initdb.d:ro
